name: nmake
on:
  push:
    branches:
      - master
jobs:
  nmake:
    name: nmake
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.MY_TOKEN}}
    - name: vcvars | build(bat)
      shell: cmd
      env: 
        vc_arch: x86
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
        build_example(GitHubCI).bat
