name: nmake
on:
  push:
    branches:
      - master
jobs:
  nmake:
    name: nmake
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.MY_TOKEN}}
    - name: vcvars | build(bat)
      shell: cmd
      env: 
        vc_arch: x86
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
        rd build_github /s /q
        mkdir build_github
        cd build_github
        echo -------------------start-------------------
        echo=
        echo -------------------init-------------------
        echo=
        echo -------------------cmake-------------------
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug
        echo -------------------MSBuild-------------------
        nmake 
        echo -------------------end-------------------
        echo=
        echo ---------------------run---------------------
        CPP_HEADERS.exe
        echo -------------------run-end-------------------
        pwd
