name: nmake
on:
  push:
    branches:
      - master
jobs:
  nmake:
    name: nmake
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
    - name: vcvars | cmake | nmake | run | email
      shell: cmd
      env: 
        vc_arch: x86
        mbox : ${{ secrets.MY_QQ_MAILBOX }}
        boxwd: ${{ secrets.MY_QQ_MAILBOX_PASSWD }}
      run: |
        chcp 65001 >log_github.txt 2>&1
        echo -------------------the commit------------------->>log_github.txt 2>&1
        git log -1 >>log_github.txt 2>&1
        echo=>>log_github.txt 2>&1
        echo -------------------start------------------->>log_github.txt 2>&1
        echo -------------------init------------------->>log_github.txt 2>&1
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch% >>log_github.txt 2>&1
        echo -------------------make dir------------------->log_github2.txt 2>&1
        rd build_github /s /q >>log_github2.txt 2>&1
        mkdir build_github >>log_github2.txt 2>&1
        cd build_github >>log_github2.txt 2>&1
        echo=>>../log_github2.txt 2>&1
        echo -------------------cmake------------------->>../log_github2.txt 2>&1
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug >>../log_github2.txt 2>&1
        echo -------------------MSBuild------------------->>../log_github2.txt 2>&1
        nmake >>../log_github2.txt 2>&1
        echo -------------------end------------------->>../log_github2.txt 2>&1
        echo=>>../log_github2.txt 2>&1
        echo ---------------------run--------------------->>../log_github2.txt 2>&1
        CPP_HEADERS.exe >>../log_github2.txt 2>&1
        echo -------------------run-end------------------->>../log_github2.txt 2>&1
        echo in：>>../log_github2.txt 2>&1
        pwd >>../log_github2.txt 2>&1
        cd ..
        type log_github.txt >log_github_all.txt
        type log_github2.txt >>log_github_all.txt
        type log_github_all.txt
        python send_email.py