name: nmake
on:
  push:
    branches:
      - master
jobs:
  nmake:
    name: nmake
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
    - name: vcvars | cmake | nmake | run
      shell: cmd
      env: 
        vc_arch: x86
        token: ${{ secrets.MY_TOKEN }}
      run: |
        chcp 65001 >log_github.txt 2>&1
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch% >>log_github.txt 2>&1
        rd build_github /s /q >log_github2.txt 2>&1
        mkdir build_github >>log_github2.txt 2>&1
        cd build_github >>log_github2.txt 2>&1
        echo -------------------start------------------->>../log_github2.txt 2>&1
        echo=>>../log_github2.txt 2>&1
        echo -------------------init------------------->>../log_github2.txt 2>&1
        echo=>>../log_github2.txt 2>&1
        echo -------------------cmake------------------->>../log_github2.txt 2>&1
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug >>../log_github2.txt 2>&1
        echo -------------------MSBuild------------------->>../log_github2.txt 2>&1
        nmake >>../log_github2.txt 2>&1
        echo -------------------end------------------->>../log_github2.txt 2>&1
        echo=>>../log_github2.txt 2>&1
        echo ---------------------run--------------------->>../log_github2.txt 2>&1
        CPP_HEADERS.exe >>../log_github2.txt 2>&1
        echo -------------------run-end------------------->>../log_github2.txt 2>&1
        echo in：>>../log_github2.txt 2>&1
        pwd >>../log_github2.txt 2>&1
        cd ..
        type log_github.txt >log_github_all.txt
        type log_github2.txt >>log_github_all.txt
        type log_github_all.txt
        git config --global user.email "telephone2021@outlook.com"
        git config --global user.name "Telephone"
        git remote set-url origin https://%token%@github.com/Telephone2019/C-Head-Files
        git add .
        git commit -m "log"
        git push --force origin master:github_action_nmake
  email:
    name: email
    runs-on: ubuntu-latest
    needs: nmake
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
        ref: github_action_nmake
    - name: send email
      uses: dawidd6/action-send-mail@master
      with:
        serveraddress: smtp.qq.com
        serverport: 465
        username: 3508065304@qq.com
        password: wbsiqdzxzxexdaje
        subject: GitHub Action | C-Head-Files | nmake
        body: file://log_github_all.txt
        to: telephone2021@outlook.com
        from: whale
        content_type: text/html